openapi: 3.0.3
info:
  title: OpenAPI schema for template walrus-template-template
components:
  schemas:
    variables:
      type: object
      required:
      - infrastructure
      properties:
        context:
          title: Context
          type: object
          description: |
            Receive contextual information. When Walrus deploys, Walrus will inject specific contextual information into this field.
          default: {}
          nullable: true
          additionalProperties:
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            hidden: true
            order: 1
        infrastructure:
          title: Infrastructure
          type: object
          description: |
            Specify the infrastructure information for deploying.
          required:
          - network_id
          properties:
            domain_suffix:
              default: cluster.local
              description: |
                Specify the domain name for discovering the service.
              nullable: true
              title: Domain Suffix
              type: string
              x-walrus-ui:
                order: 2
            network_id:
              description: |
                Specify the ID of the Docker network where the service applies.
              title: Network Id
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 2
        architecture:
          title: Architecture
          type: string
          description: |
            Specify the deployment architecture, select from standalone or replication.
          default: standalone
          enum:
          - standalone
          - replication
          nullable: true
          x-walrus-ui:
            group: Basic
            order: 3
        replication_readonly_replicas:
          title: Replication Readonly Replicas
          type: number
          description: |
            Specify the number of read-only replicas under the replication deployment.
          default: 1
          enum:
          - 1
          - 3
          - 5
          nullable: true
          x-walrus-ui:
            group: Basic
            order: 4
            showIf: architecture=replication
        engine_version:
          title: Engine Version
          type: string
          description: |
            Specify the deployment engine version, select from https://hub.docker.com/r/bitnami/redis/tags.
          default: "7.0"
          nullable: true
          x-walrus-ui:
            group: Basic
            order: 5
        password:
          title: Password
          type: string
          description: |
            Specify the account password. The password must be 8-32 characters long and start with any letter, number, or symbols: ! # $ % ^ & * ( ) _ + - =.
            If not specified, it will use the first 16 characters of the username md5 hash value.
          format: password
          nullable: true
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 8
        resources:
          title: Resources
          type: object
          description: |
            Specify the computing resources.
          nullable: true
          properties:
            cpu:
              default: 0.25
              description: |
                Specify the CPU core number. Unit is core.
              nullable: true
              title: Cpu
              type: number
              x-walrus-ui:
                order: 1
            memory:
              default: 1024
              description: |
                Specify the memory size. Unit is megabyte.
              nullable: true
              title: Memory
              type: number
              x-walrus-ui:
                order: 2
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 9
      x-walrus-ui:
        groupOrder:
        - Basic
